### ISSUE TITLE
Duplicated username

### ISSUE THREAD

**Issue by TanyaYovkova-start** [lgoychev/Team-Bration#10]
We can create two identical usernames. 
1. Enter "EuroinsLtd" in a usernamefield in a login form 
2. Enter a password "assurance" in a passwordfield in a login form
3. Click to "submit" button
4. Repeat the upper steps 

Actual result: We have 2 usernames with identical usernames
Expected result: When we entered the same username in the usernamefield a message must alarm us that this username is allready used.

**Comment by VSabev** [comment]
The login into an user interface will be a part of integration process.  Any integration and implementation testing of the application including interface is not in the scope of this project
