### ISSUE TITLE
Empty recorded XML file with next invoice number

### ISSUE THREAD

**Issue by TanyaYovkova-start** [lgoychev/Team-Bration#13]
The JCNEx give the next invoice number of an empty recorded xml file
1. Click "browse" and choose empty XML file in the first field
2. Click "browse" and choose output folder in the second field
3.  Press a "Submit" button
4. Check the invoice.

Actual result: The process is completed prompt message appeared and display “The XML file is successfully enriched. 
Expected result: The empty file is not a real invoice and it must be invalidated. The program must not give a number of a file without invoice

**Comment by nrayanov** [comment]
Bug fixed, we will throw exception if the file is empty.
