### ISSUE TITLE
Accepted "_" symbol instead “-” 

### ISSUE THREAD

**Issue by TanyaYovkova-start** [lgoychev/Team-Bration#14]
Accepted + symbol instead “-”
Recorded file with invalid symbol and without an error message
1. Click  the browse button
2.  Input file which PONumber  include  ”_” symbol
3.  Press a “submit” button

Actual result: The process is completed 
Expected result: Error message “No Contract number available in PONumber”

**Comment by VSabev** [comment]
Bug was fixed with second Build.
