### ISSUE TITLE
Incorrect message after not enough space in the chosen output folder

### ISSUE THREAD

**Issue by TanyaYovkova-start** [lgoychev/Team-Bration#17]
1. Click browse button and choose the file
2. Click browse button and choose the output folder located in a disc without enough free space 
3. Click “Submit” button

Actual result: The process is complete and Prompt message appeared the message “XML file was successfully enriched”
Expected result: There must be occurred a specifically error message.

**Comment by nrayanov** [comment]
Bug fixed, we will throw exception: "Not enough space on %"
