### ISSUE TITLE
Create a functionality to parse  the XML file.

### ISSUE THREAD

**Issue by lgoychev** [lgoychev/Team-Bration#3]
Use the SRS document to create a general functionality of JCNEx to parse and extract the Contract number ofPONumber on source XML file. 
the general requirements: 
- PONumber is create form ID number and Contract number
- delimiter symbol is "-"
- Contract number need to be present in output xml file with new tag <Contract>

**Comment by nrayanov** [comment]
Version 1 of JCNEx is created.
Extracts Contract number from PONumber to tag Contract.
Currently modified the source file.

To do:
1. Better exceptions
2. Modify output file, not source
