### ISSUE TITLE
Create a mockups about user interface.

### ISSUE THREAD

**Issue by lgoychev** [lgoychev/Team-Bration#5]
Need to create mockups to present how the user interface should be look.
The application should be have:
- Login screen : username and password
- Choose file screen
- Processing screen
- Prompt message for successfully or error when it is done.

**Comment by lgoychev** [comment]
The mokcups are created see on https://moqups.com/lubaks@gmail.com/zT6n795I

**Comment by nrayanov** [comment]
Looks good, one thing needs to be fixed though. Successful enrichment mock-up is not very good (see "enriched!").

**Comment by lgoychev** [comment]
Nice catch!
The nessage is changed to : "The Contract number was successfully extract!"
See how it looks now.

![done](https://cloud.githubusercontent.com/assets/13354359/9391635/82de9352-4780-11e5-98dc-68004ec78e8a.png)

**Comment by nrayanov** [comment]
Should be "The Contract number is successfully extracted!.

**Comment by lgoychev** [comment]
fixed in moqups and in the code.

![done_moqup](https://cloud.githubusercontent.com/assets/13354359/9400192/3e9768bc-47c7-11e5-8803-b3cdba06efe5.png)
![done_code](https://cloud.githubusercontent.com/assets/13354359/9400193/3f70dac0-47c7-11e5-8fc6-30a43f4ab2dd.png)

**Comment by nrayanov** [comment]
Looks good now!
